name: blocs_copyclient_example
description: A demo projet for the AStA Copyclient business logic
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blocs_copyclient:
    path: ../
  barcode_scan: ^1.0.0
  flutter_bloc: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
