image: bchabord/flutter-android-docker:latest

stages:
  - build
  - test

build_example:
  stage: build
  script:
    - cd example
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - flutter build apk
  artifacts:
    paths:
    - example/build/app/outputs/apk

unit_test:
  stage: test
  script:
    - pub run test
  artifacts:
    paths:
      - test/out
