image: bchabord/flutter-android-docker:latest

stages:
  - build

build_example:
  stage: build
  script:
    - cd example
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - flutter build apk
  artifacts:
    paths:
    - example/build/app/outputs/apk
