name: blocs_copyclient
version: 0.1.0
description: >-
    Library that supplies the Business Logic Components
    for the AStA Copyclient
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
  bloc: ^0.14.2
  http: ^0.12.0+2
  logging: ^0.11.3+2
  quiver: ^2.0.3
  cli_repl: ^0.2.0+1
  image: ^2.1.4
  pdf: ^1.3.18
  csv: ^4.0.3

dev_dependencies:
  test: ^1.5.1
