name: blocs_copyclient
version: 2.0.0
description: >-
  Library that supplies the Business Logic Components
  for the AStA Copyclient
author: Leon Tappe <ltappe@asta.upb.de>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.3.0
  bloc: ^7.0.0
  http: ^0.13.3
  logging: ^1.0.1
  quiver: ^3.0.1
  cli_repl: ^0.2.2
  image: ^3.0.2
  pdf: ^3.4.2
  csv: ^5.0.0

dev_dependencies:
  test: ^1.17.10
